import type { AppAnalysisConfig } from './standard';
import { APP_META } from '../config';

/** Lo propio de Rutinas Matematizadas dentro del estándar de análisis (ver ESTANDAR-ANALISIS.md). */
export const RUTINAS_ANALYSIS: AppAnalysisConfig = {
  appName: APP_META.name,
  moduleLabel: `Módulo de Evaluación Formativa Digital - ${APP_META.name}`,
  title: 'Análisis Metacognitivo del Diseño Didáctico',
  subtitle: 'Análisis cualitativo y cuantitativo del proceso cognitivo basado en el modelo de autorregulación de Zimmerman y Moylan.',
  appropriation: {
    blurb: 'Índice sintético que combina la exactitud de las asignaciones coherentes en la jornada (50%), la eficiencia procedimental en decisiones (30%) y la detención reflexiva mediante la consulta de devoluciones didácticas (20%).',
    weights: '50 / 30 / 20',
  },
  gaugeIntro: {
    title: 'Evaluación Científica de Autorregulación',
    p1: 'Estos 10 indicadores miden con precisión tu conducta de diseño didáctico al matematizar la jornada de rutinas de cuidado, organizados en dos dimensiones: tu capacidad de monitoreo metacognitivo autorregulado (Zimmerman & Moylan, 2009) y tu competencia disciplinar en matematización de rutinas de cuidado (Freudenthal; BCEP).',
    hint: 'Haz clic en cualquier indicador para ver su fórmula y tip didáctico.',
  },
  dimB: { kicker: 'Evaluación de Dominio Disciplinar', title: 'DIMENSIÓN 2: Competencia en Matematización de Rutinas de Cuidado', subIndexLabel: 'Sub-índice ICMR' },
  indicators: {
    IM1: { name: 'IM1. Vigilancia Cognitiva Sostenida', authors: 'Zimmerman & Moylan (2009) — Fase de Ejecución: Autoobservación', description: 'Mide la atención reflexiva evaluando la proporción de acciones consecutivas (ubicar, decidir, consultar) separadas por un intervalo óptimo de deliberación (entre 5 y 60 segundos). Previene el arrastre impulsivo de tarjetas.', tip: 'Tómate un breve tiempo (más de 5 segundos) antes de realizar cada cambio para reflexionar sobre su impacto didáctico.' },
    IM2: { name: 'IM2. Proporción de Detención Reflexiva', authors: 'Zimmerman & Moylan (2009) — Fase de Ejecución: Autoobservación', description: 'La tasa de consulta teórica (devoluciones abiertas) respecto a las decisiones de diseño. Indica una disposición hacia la autoobservación reflexiva antes del diseño final.', tip: 'No te limites a mover tarjetas: haz pausas para consultar la devolución didáctica de la app, también cuando tu combinación sea correcta.' },
    IM3: { name: 'IM3. Autocorrección y Detección de Errores', authors: 'Zimmerman & Moylan (2009) — Fase de Ejecución: Autocontrol', description: 'Evalúa la capacidad de identificar incongruencias didácticas mediante el análisis de las devoluciones del sistema y su enmienda hacia un estado óptimo: 50 puntos por leer la devolución y 50 por reasignar de forma coherente. Si no hubo errores, se evalúa la verificación proactiva de tus combinaciones con la devolución.', tip: 'Si cometes un desajuste didáctico, lee la devolución didáctica y luego reajusta la situación matemática para corregirlo.' },
    IM4: { name: 'IM4. Aprovechamiento de Retroalimentación', authors: 'Zimmerman & Moylan (2009) — Fase de Ejecución: Autocontrol', description: 'Determina en qué medida la estudiante consulta las devoluciones efectivamente disponibles (de rutina, de situación y por fase).', tip: 'Utiliza el botón «Devolución Didáctica» cada vez que configures una rutina, una situación matemática o una fase para incorporar el andamiaje teórico.' },
    IM5: { name: 'IM5. Resiliencia al Fracaso y Reajuste Cognitivo', authors: 'Panadero & Alonso-Tapia (2014) — Ciclo Adaptativo post-error', description: 'Capacidad de reajuste ante un conflicto didáctico: se corrige en la decisión siguiente o más adelante sobre la misma rutina (100), o al menos se lee su devolución (50). Sin errores no se penaliza.', tip: 'Usa los errores como palancas de aprendizaje. Intenta resolver los desajustes de tu planificación de forma prioritaria.' },
    IM6: { name: 'IM6. Alineación con la Secuencia de la Jornada', authors: 'BCEP (2018) — Progresión de la jornada pedagógica', description: 'Evalúa si la estudiante respeta la progresión natural de la jornada (inicio, desarrollo, cierre) antes de decidir sobre el cierre. Penaliza decidir el cierre sin haber consolidado las fases previas.', tip: 'Dedica tiempo a estructurar el Inicio y el Desarrollo antes de consolidar el cierre didáctico de la jornada.' },
    IM7: { name: 'IM7. Fluidez y Control de Carga Cognitiva', authors: 'Zimmerman & Moylan (2009) — Fase de Ejecución: Autoobservación', description: 'Mide la eficiencia cognitiva penalizando las modificaciones redundantes sobre una misma rutina, indicador de duda sistemática o sobrecarga cognitiva.', tip: 'Planifica con mayor convicción conceptual. Muchos cambios sobre una sola rutina indican sobrecarga de decisiones.' },
    IM8: { name: 'IM8. Intencionalidad del Ensayo y Error', authors: 'Freudenthal (1991) — Matematización realista', description: 'Proporción de decisiones didácticas idóneas e intencionadas sobre el total de decisiones en el espacio de diseño didáctico.', tip: 'Revisa las Bases Curriculares y los fundamentos didácticos para que cada decisión esté mejor justificada.' },
    IM9: { name: 'IM9. Precisión Predictiva Planificada', authors: 'BCEP (2018) — Modelo mental de coherencia rutina-matemática', description: 'Porcentaje de rutinas matematizadas correctamente en su primera decisión, lo que demuestra anticipación didáctica previa a la acción.', tip: 'Estudia bien las compatibilidades didácticas (ej. Higiene con Secuencias Temporales) para acertar desde el primer intento.' },
    IM10: { name: 'IM10. Apropiación de Códigos de Formulación', authors: 'Brousseau (1997) — Teoría de Situaciones Didácticas: Formulación', description: 'Evalúa la efectividad de las decisiones tomadas en la fase central de Desarrollo, donde se formulan las situaciones matemáticas del núcleo de la experiencia. Una fase de Desarrollo vacía se considera omitida (0).', tip: 'Asegúrate de incluir y decidir con criterio las situaciones de la fase central (Desarrollo) de tu jornada.' },
  },
  digcomp: {
    implement41: 'Las 7 rutinas de cuidado con sus 6 situaciones matemáticas y la verificación de coherencia funcionan como un instrumento de evaluación formativa que diagnostica en tiempo real la capacidad de la estudiante para matematizar rutinas cotidianas.',
    implement42: 'Los 10 indicadores BCT (organizados en IMMZ e ICMR), la Bitácora de Monitoreo Activo, el historial de interacciones y las métricas de Calidad Didáctica (alineación BCEP, densidad, diversidad, coherencia) constituyen analíticas de aprendizaje procesables por el docente.',
    implement43: 'Las Devoluciones Didácticas contextualizadas por cada combinación rutina-situación matemática ofrecen retroalimentación inmediata, específica y pedagógicamente fundamentada que explica por qué una combinación es pertinente o forzada, permitiendo a la estudiante ajustar sus decisiones de planificación.',
  },
  foundation: 'Este diagnóstico traduce la secuencia de acciones de la participante en dos dimensiones complementarias. La Dimensión A (Monitoreo Metacognitivo) se fundamenta en el modelo cíclico de autorregulación de Zimmerman y Moylan (2009), específicamente en la fase de ejecución, donde el autocontrol y la auto-observación permiten a la estudiante supervisar sus decisiones de planificación y ajustar estrategias en tiempo real. La Dimensión B (Competencia en Matematización de Rutinas de Cuidado) se sustenta en el enfoque de matematización realista de Freudenthal (1991) y en las Bases Curriculares de Educación Parvularia (BCEP, 2018), donde la matematización emerge orgánicamente de los momentos de cuidado cotidiano. Ambas dimensiones se articulan con el Área 4 del marco DigCompEdu (Evaluación y Retroalimentación), que abarca el diseño de instrumentos evaluativos digitales (4.1), las analíticas de aprendizaje (4.2) y la retroalimentación orientada a la toma de decisiones (4.3). El Diario de Campo complementa los indicadores conductuales con la voz de la estudiante sobre su propio proceso, permitiendo triangular datos de comportamiento con datos de autorreporte.',
};
